# FM5121  Homework 1
### Due:  September 15, Midnight.  
### Ping Zhong zhong338@umn.edu 

### Solve the linear system of equations by "equation operations" and back-substitution. Show steps.


1.  $$\begin{eqnarray*} 
10x - y &=& 8\\
x  + y &=& 3
\end{eqnarray*}$$







$$\begin{eqnarray*}  
10x - 8 = y\\
x  + 10x -8 = 3 \\
11x = 11, x = 1 \\ 
y = 10x - 8 = 2  
\end{eqnarray*}$$

2. 
$$\begin{eqnarray*} 
x_1 - x_2 + 4x_3 &=& -3\\
3x_1 + x_2 -x_3 &=& 8\\
x_1 + x_2 + x_3 &=& 2  
\end{eqnarray*}$$

$$\begin{eqnarray*}  
① +③: 2x_1 +5x_3 = -1\\
 ① +②: 4x_1 +3x_3 = 5\\
4x_1 +3x_3 - 2(2x_1 +5x_3)= 5 -2(-1)= 7\\ 
-7x_3 = 7, x_3 = -1\\
4x_1 +3x_3 = 4x_1 +3(-1) = 5, x_1 = 2\\
x_1 -x_2 +4x_3 = 2 - x_2 +4(-1) = -3, x_2=1\\
\end{eqnarray*}$$

3.  
$$\begin{eqnarray*} 
x + y  -z &=& 6\\
x +2y + z &=& 0
\end{eqnarray*}$$

$$\begin{eqnarray*}
x+y = 6+z ...①\\
x+2y = -z ...②\\
② - ①: y = -z -6 -z = -6-2z \\
x-6-2z = 6 +z \\
x = 12+3z
\end{eqnarray*} $$ for any z ∈ R

That is to say, there are infinitely many solutions.

### Vector independence and matrix rank 

4. Determine if the columns of the matrix $A = \begin{pmatrix}
0 & 1& 5 \\
1 & 2 & -1\\
5 & 8 & 0\\
\end{pmatrix}$ are linear independent.  Calculate the rank of the matrix $A$.

Let $v_j$ to represent the $j-th$ column vector, we want to check if the column vector $v_j$ are linearly independent. 
$$ 
c_1 V_1 + c_2 V_2 + c_3 V_3 = c_1 \begin{pmatrix}
0 \\
1 \\
5 \\
\end{pmatrix} 
+ c_2 \begin{pmatrix}
1 \\
2 \\
8 \\
\end{pmatrix}
+ c_3 \begin{pmatrix}
5 \\
-1 \\
0 \\
\end{pmatrix}
= 0 \\
c_2 +5c_3 = 0 \\
c_1 +2c_2 -c_3 = 0\\
5c_1 +8c_2 = 0\\
c_1 =c_2=c_3 = 0
$$
Thurs the columns of the matrix A are linearly independent, and Rank(A) = 3. 

### Matrix multiplication

5. Let $A = \begin{pmatrix}
1 & 2\\
5 & 4\\
2 & 3\\
\end{pmatrix}$, $B = \begin{pmatrix}
3 & -2 \\
-2 & 1 \\
\end{pmatrix}$, calculate $AB$.  What can you say about $BA$?

$$AB = \begin{pmatrix}
1 & 2\\
5 & 4\\
2 & 3\\
\end{pmatrix} \begin{pmatrix}
3 & -2 \\
-2 & 1 \\
\end{pmatrix} = \begin{pmatrix}
3-4 & -2+2\\
15-8 & -10+4\\
6-6 & -4+3\\
\end{pmatrix} = \begin{pmatrix}
-1 & 0\\
7 & -6\\
0 & -1\\
\end{pmatrix}
$$

AB ≠ BA, can't caculate BA since 2x2 matrix can't multiply 3x2 matrix. 

6. Let $A = \begin{pmatrix}
2 & 5\\
-3 & 1\\
\end{pmatrix}$, $B = \begin{pmatrix}
4 & -5 \\
3 & k \\
\end{pmatrix}$, What value(s) of $k$ will make $AB = BA$

$AB = \begin{pmatrix}
2 & 5\\
-3 & 1\\
\end{pmatrix}$ $\begin{pmatrix}
4 & -5 \\
3 & k \\
\end{pmatrix}$ = $\begin{pmatrix}
23 & -10 +5k \\
-9 & 15+k \\
\end{pmatrix}$

$BA = \begin{pmatrix}
4 & -5 \\
3 & k \\
\end{pmatrix} \begin{pmatrix}
2 & 5\\
-3 & 1\\
\end{pmatrix} = \begin{pmatrix}
23 & 15\\
6-3k & 15+k\\
\end{pmatrix}$

$\begin{pmatrix}
23 & -10 +5k \\
-9 & 15+k \\
\end{pmatrix} = \begin{pmatrix}
23 & 15\\
6-3k & 15+k\\ 
\end{pmatrix}$
$$ k=5 $$

### Matrix Inversion

7. Use determinants to determine which of the following matrices are invertible.

$A = \begin{pmatrix}
3 & -9\\
2 & 6\\
\end{pmatrix}$, 
$B = \begin{pmatrix}
4 & -9 \\
0 & 5 \\
\end{pmatrix}$
$C = \begin{pmatrix}
6 & -9 \\
-4 & 6 \\
\end{pmatrix}$

$$
det(A) = 18 -2(-9) = 36\\
det(B) = 20 -0 = 20\\
det(C) = 36-36 = 0 
$$
Thus, A and B is invertible, and C is not invertible. 

8. Manually find the inverse of the matrix $A= \begin{pmatrix}
1 & -2 & -1\\
-1 & 5 & 6\\
5 & -4 & 5\\
\end{pmatrix}$
, if it exists. 


$$[AI]= \begin{pmatrix}
1 & -2 & -1 & 1 & 0 & 0\\
-1 & 5 & 6 & 0 & 1 & 0\\
5 & -4 & 5 & 0 & 0 & 1\\
\end{pmatrix} = \begin{pmatrix}
0 & 3 & 5 & 1 & 1 & 0\\
-1 & 5 & 6 & 0 & 1 & 0\\
5 & -4 & 5 & 0 & 0 & 1\\
\end{pmatrix} = \begin{pmatrix}
0 & 3 & 5 & 1 & 1 & 0\\
-1 & 5 & 6 & 0 & 1 & 0\\
5 & -7 & 0 & -1 & -1 & 1\\
\end{pmatrix} = \begin{pmatrix}
0 & 18 & 30 & 6 & 6 & 0\\
-5 & 25 & 30 & 0 & 5 & 0\\
5 & -7 & 0 & -1 & -1 & 1\\
\end{pmatrix} = \begin{pmatrix}
0 & 3 & 5 & 1 & 1 & 0\\
-5 & 7 & 0 & -6 & -1 & 0\\
5 & -7 & 0 & -1 & -1 & 1\\
\end{pmatrix} = \begin{pmatrix}
0 & 3 & 5 & 1 & 1 & 0\\
-5 & 7 & 0 & -6 & -1 & 0\\
0 & 0 & 0 & -7 & -2 & 1\\
\end{pmatrix}
$$
Since it's unable to find $[AI]$, the inverse of the matrix $A$ doesn't exisit. 

Write Python code to verify your results.

In [13]:
import numpy as np
import scipy.linalg as la

In [23]:
import sympy
from sympy import symbols, Eq, solve 

In [26]:
### 1. ---------------------------------------
x,y = symbols('x y')
eq1 = Eq(10*x -y ,8)
eq2 = Eq(x +y , 3)
sol_dict = solve((eq1,eq2),(x,y))
print(f'x={sol_dict[x]}')
print(f'y={sol_dict[y]}')

x=1
y=2


In [27]:
### 2. ---------------------------------------
x1,x2,x3 = symbols('x1 x2 x3')
eq1 = Eq(x1 -x2 +4*x3 ,-3)
eq2 = Eq(3*x1 +x2 -x3 ,8)
eq3 = Eq(x1 +x2 +x3 ,2)
sol_dict = solve((eq1,eq2,eq3),(x1,x2,x3))
print(f'x1={sol_dict[x1]}')
print(f'x2={sol_dict[x2]}')
print(f'x3={sol_dict[x3]}')

x1=2
x2=1
x3=-1


In [30]:
### 3. ---------------------------------------
x,y,z = symbols('x y z')
eq1 = Eq(x +y -z ,6)
eq2 = Eq(x +2*y +z, 0)
sol_dict = solve((eq1,eq2),(x,y,z))
print(f'x={sol_dict[x]}')
print(f'y={sol_dict[y]}')

x=3*z + 12
y=-2*z - 6


In [41]:
### 4. ---------------------------------------
A = np.array([[0,1,5],[1,2,-1],[5,8,0]])
b = np.array([0,0,0])
x = la.inv(A) @b

print(x)

# Find the rank(A):
rank = np.linalg.matrix_rank(A)
print("Rank of the given Matrix A is: ", rank)

[0. 0. 0.]
Rank of the given Matrix A is:  3


In [10]:
### 5. ---------------------------------------
A = np.array([[1,2],[5,4],[2,3]])
B = np.array([[3,-2],[-2,1]])
x1 = A @ B
print("AB is :\ ",x1)

AB is :
 [[-1  0]
 [ 7 -6]
 [ 0 -1]]


In [57]:
### 6. ------------------------------------------
# Let k =5
A = np.array([[2,5],[-3,1]])
B = np.array([[4,-5],[3,5]])
print("Check if AB =BA: ")
print(A@B)
print(B@A)

Check if AB =BA: 
[[23 15]
 [-9 20]]
[[23 15]
 [-9 20]]


In [39]:
### 7. ------------------------------------------
A = np.array([[3,-9],[2,6]])
B = np.array([[4,-9],[0,5]])
C = np.array([[6,-9],[-4,6]])
detA = np.linalg.det(A)
detB = np.linalg.det(B)
detC = np.linalg.det(C)
print("Determinant of given matrix A B and C: ",detA, detB, detC)
print("So the matrix A and matrix B are invertible and matrix C is not invertible.")

Determinant of given matrix A B and C:  36.0 19.999999999999996 0.0
So the matrix A and matrix B are invertible and matrix C is not invertible.


In [47]:
### 8. ------------------------------------------
A = np.array([[1,-2,-1],[-1,5,6],[5,-4,5]])
detA = np.linalg.det(A)
if detA == 0.0:
    print("The inverse of the matrix A doesn't exist.")
else:
    X = np.linalg.inv(A)
    print('The inverse of the matrix A is \n ',A)

The inverse of the matrix A doesn't exist.
